using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using TaskForge.API.DTOs;
using TaskForge.API.Interfaces;

namespace TaskForge.API.Controllers;

[ApiController]
[Authorize]
public class ActivitiesController : ControllerBase
{
    private readonly IActivityService _activityService;

    public ActivitiesController(
        IActivityService activityService)
    {
        _activityService = activityService;
    }


    // =====================================================
    // GET ISSUE ACTIVITIES
    // Admin + Project Manager + Developer
    // =====================================================

    [HttpGet("api/issues/{issueId}/activities")]
    [Authorize(
        Roles = "Admin,ProjectManager,Developer"
    )]
    public async Task<ActionResult<IEnumerable<ActivityDto>>> GetByIssue(
        int issueId)
    {
        var activities =
            await _activityService.GetByIssueAsync(
                issueId);

        return Ok(activities);
    }


    // =====================================================
    // GET PROJECT ACTIVITIES
    // Admin + Project Manager + Developer
    // =====================================================

    [HttpGet("api/projects/{projectId}/activities")]
    [Authorize(
        Roles = "Admin,ProjectManager,Developer"
    )]
    public async Task<ActionResult<IEnumerable<ActivityDto>>> GetByProject(
        int projectId)
    {
        var activities =
            await _activityService.GetByProjectAsync(
                projectId);

        return Ok(activities);
    }


    // =====================================================
    // MANUAL ACTIVITY CREATION
    //
    // IMPORTANT:
    // Do NOT accept userId from the client.
    //
    // Activities generated by the application should use
    // the authenticated user.
    // =====================================================

    [HttpPost("api/activities")]
    [Authorize(
        Roles = "Admin,ProjectManager,Developer"
    )]
    public async Task<ActionResult<ActivityDto>> Create(
        int? projectId,
        int? issueId,
        string action)
    {
        var currentUserId =
            User.FindFirst(
                System.Security.Claims.ClaimTypes.NameIdentifier
            )?.Value;

        if (!int.TryParse(
                currentUserId,
                out var userId))
        {
            return Unauthorized(
                "Authenticated user could not be identified.");
        }

        if (string.IsNullOrWhiteSpace(action))
        {
            return BadRequest(
                "Activity action is required.");
        }

        var activity =
            await _activityService.CreateAsync(
                userId,
                projectId,
                issueId,
                action);

        return Ok(activity);
    }
}